### ISSUE TITLE
sbt fails after fresh clone

### ISSUE THREAD

**Issue by augi** [scalapb/protoc-bridge#10]
I executed `sbt ++2.12.4 test`.

The important part:
```
[warn]  :: com.jsuereth#sbt-pgp;1.0.0: not found
[warn]  :: com.github.gseitz#sbt-release;1.0.0: not found
[warn]  :: org.xerial.sbt#sbt-sonatype;1.0: not found
```

Full log:
```
[warn]  module not found: com.jsuereth#sbt-pgp;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\augustyn\.ivy2\local\com.jsuereth\sbt-pgp\scala_2.12\sbt_1.0\1.0.0\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/jsuereth/sbt-pgp_2.12_1.0/1.0.0/sbt-pgp-1.0.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\augustyn\.sbt\preloaded\com.jsuereth\sbt-pgp\1.0.0\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/augustyn/.sbt/preloaded/com/jsuereth/sbt-pgp_2.12_1.0/1.0.0/sbt-pgp-1.0.0.pom
[warn]  module not found: com.github.gseitz#sbt-release;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\augustyn\.ivy2\local\com.github.gseitz\sbt-release\scala_2.12\sbt_1.0\1.0.0\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/gseitz/sbt-release_2.12_1.0/1.0.0/sbt-release-1.0.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\augustyn\.sbt\preloaded\com.github.gseitz\sbt-release\1.0.0\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/augustyn/.sbt/preloaded/com/github/gseitz/sbt-release_2.12_1.0/1.0.0/sbt-release-1.0.0.pom
[warn]  module not found: org.xerial.sbt#sbt-sonatype;1.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.xerial.sbt/sbt-sonatype/scala_2.12/sbt_1.0/1.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.xerial.sbt/sbt-sonatype/scala_2.12/sbt_1.0/1.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\augustyn\.ivy2\local\org.xerial.sbt\sbt-sonatype\scala_2.12\sbt_1.0\1.0\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/xerial/sbt/sbt-sonatype_2.12_1.0/1.0/sbt-sonatype-1.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\augustyn\.sbt\preloaded\org.xerial.sbt\sbt-sonatype\1.0\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/augustyn/.sbt/preloaded/org/xerial/sbt/sbt-sonatype_2.12_1.0/1.0/sbt-sonatype-1.0.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.jsuereth#sbt-pgp;1.0.0: not found
[warn]  :: com.github.gseitz#sbt-release;1.0.0: not found
[warn]  :: org.xerial.sbt#sbt-sonatype;1.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.jsuereth:sbt-pgp:1.0.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.github.gseitz:sbt-release:1.0.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          org.xerial.sbt:sbt-sonatype:1.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.jsuereth:sbt-pgp:1.0.0 (scalaVersion=2.12, sbtVersion=1.0) (C:\Users\augustyn\Documents\protoc-bridge\project\pgp.sbt#L1-2)
[warn]            +- default:protoc-bridge-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.github.gseitz:sbt-release:1.0.0 (scalaVersion=2.12, sbtVersion=1.0) (C:\Users\augustyn\Documents\protoc-bridge\project\release.sbt#L1-2)
[warn]            +- default:protoc-bridge-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          org.xerial.sbt:sbt-sonatype:1.0 (scalaVersion=2.12, sbtVersion=1.0) (C:\Users\augustyn\Documents\protoc-bridge\project\sonatype.sbt#L1-2)
[warn]            +- default:protoc-bridge-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.jsuereth#sbt-pgp;1.0.0: not found
[error] unresolved dependency: com.github.gseitz#sbt-release;1.0.0: not found
[error] unresolved dependency: org.xerial.sbt#sbt-sonatype;1.0: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2381)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.jsuereth#sbt-pgp;1.0.0: not found
[error] unresolved dependency: com.github.gseitz#sbt-release;1.0.0: not found
[error] unresolved dependency: org.xerial.sbt#sbt-sonatype;1.0: not found
```

I tried to search for the requesting versions of the referenced artifacts manually and it seems that they really don't exist:
* `com.jsuereth#sbt-pgp;1.0.0` - I found `1.1.0` only (see [this](https://dl.bintray.com/sbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/))
* `com.github.gseitz#sbt-release;1.0.0` - only `1.0.6` and `1.0.7` is available for 2.12, see [this](https://dl.bintray.com/sbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/)
* `org.xerial.sbt#sbt-sonatype;1.0` - only `2.0` and `2.1` is available, see [this](https://repo1.maven.org/maven2/org/xerial/sbt/sbt-sonatype_2.12_1.0/)

**Comment by thesamet** [comment]
We are cross-building for 0.13.x and 1.x, to compile for SBT 1.x (which implies Scala 2.12), use `^^ 1.0.4 test`

See http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt-cross-building

**Comment by augi** [comment]
Sorry for my silly questions, I'm new to sbt (I'm using Gradle for all my projects).
1. `sbt ^^ 1.0.4 test` just wrotes `The syntax of the command is incorrect.` :(
2. Do you have any trick how to import the project to IntelliJ IDEA? If I try to import the project, I'm ending with the _missing dependencies_ errors as shown above. The change in #11 fixed it for me.
3. How is it ensured that the TravisCI build will continue working after they switch from 0.13.16 to different sbt version?

**Comment by thesamet** [comment]
My bad, from some reason I thought this issue is on sbt-protoc and not on protoc-bridge. I put a note on my earlier comment.

The problem was that there was no `project/build.properties` in this repository so on travis (and my desktop) it was using 0.13.x, while your system probably has 1.x. In 5e77e21 I added that file and if you rebase then things should work.

I think this would address all the 3 questions you posted above. Let me know if there's anything left open. Thanks for working on this!

**Comment by augi** [comment]
Yes, the missing `project/build.properties` was the issue and it's working now :) It's what #11 actually tried to fix :)

**Comment by thesamet** [comment]
:+1:
