### ISSUE TITLE
protoc-bridge 0.7.11 does not work with Java8 on windows

### ISSUE THREAD

**Issue by xuwei-k** [scalapb/protoc-bridge#56]
https://ci.appveyor.com/project/thesamet/sbt-protoc/builds/28406096/job/qay6h7s0464r5fwy#L1262

```
[info] [error] java.lang.UnsupportedClassVersionError: protocbridge/frontend/BridgeApp has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 54.0
[info] [error] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[info] [error] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
[info] [error] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[info] [error] 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
[info] [error] 	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
[info] [error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
[info] [error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
[info] [error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[info] [error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
[info] [error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
[info] [error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
[info] [error] 	at protocbridge.frontend.WindowsPluginFrontend$.createWindowsScript(WindowsPluginFrontend.scala:47)
[info] [error] 	at protocbridge.frontend.WindowsPluginFrontend$.prepare(WindowsPluginFrontend.scala:21)
[info] [error] 	at protocbridge.ProtocBridge$.$anonfun$runWithGenerators$1(ProtocBridge.scala:117)
[info] [error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[info] [error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[info] [error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[info] [error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[info] [error] 	at scala.collection.immutable.List.map(List.scala:298)
[info] [error] 	at protocbridge.ProtocBridge$.runWithGenerators(ProtocBridge.scala:116)
[info] [error] 	at protocbridge.ProtocBridge$.run(ProtocBridge.scala:81)
[info] [error] 	at sbtprotoc.ProtocPlugin$.executeProtoc(ProtocPlugin.scala:172)
[info] [error] 	at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:209)
[info] [error] 	at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:294)
[info] [error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$7(ProtocPlugin.scala:302)
[info] [error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[info] [error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:146)
[info] [error] 	at sbt.util.Difference.apply(Tracked.scala:323)
[info] [error] 	at sbt.util.Difference.apply(Tracked.scala:303)
[info] [error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:142)
[info] [error] 	at sbt.util.Difference.apply(Tracked.scala:323)
[info] [error] 	at sbt.util.Difference.apply(Tracked.scala:298)
[info] [error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:141)
[info] [error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$1(ProtocPlugin.scala:308)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[info] [error] 	at sbt.Execute.work(Execute.scala:290)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:844)
[info] [error] (Compile / protocGenerate) java.lang.UnsupportedClassVersionError: protocbridge/frontend/BridgeApp has been compi
```

**Comment by vagola** [comment]
gg can't use akka grpc

**Comment by thesamet** [comment]
@vagola This specific issue has been fixed. In order to move forward, please file a new issue and provide Windows version, JVM version, ScalaPB compiler version, sbt-protoc version and the exact error you are getting. Thank you!
